# Generated by Django 5.2.5 on 2025-09-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
