# Generated by Django 4.2.14 on 2025-07-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
