# Generated by Django 4.2.14 on 2025-07-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0002_menucategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
