# Generated by Django 5.2.5 on 2025-09-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('management', 'Management')], default='customer', max_length=20),
        ),
    ]
