# Generated by Django 5.2.7 on 2025-10-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0004_contact_tablereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
